/*---------------------------------------------------------------------------------------------
 *  Copyright (c) BeCoder contributors. All rights reserved.
 *  Licensed under GPL-3.0-or-later. See LICENSE in the project root.
 *--------------------------------------------------------------------------------------------*/

import * as path from 'path';
import { randomUUID } from 'crypto';
import { stripVTControlCharacters } from 'util';
import * as vscode from 'vscode';
import { CheckerRun, CphExecutor, JudgeRun } from './execution';
import { JudgeSession } from './judgeSession';
import { StoredProblem, ProblemStore } from './problemStore';
import { displayOutput } from './outputPresentation';
import { acquireWorkspaceLease } from './workspaceLease';
import { diffOutput, DiffResult } from './diffOutput';

const labels: Record<string, [string, string]> = {
	usageInstructions: ['Usage Instructions', '使用说明'], invocationFormat: ['Invocation Format', '调用格式'], documentation: ['Documentation', '文档'],
	exitCodes: ['Your script should exit with code 0 for success (Pass) and non-zero for failure (Fail).', '退出代码 0 表示成功（通过），非零表示失败（不通过）。'],
	expectedBehavior: ['Your script receives these file paths as positional arguments. You can read them like this:', '您的脚本将被调用，并将这些文件的路径作为位置参数。您可以像这样读取它们：'],
	argScriptPath: ['The full filesystem path to your Python checker script.', '您的 Python 判题脚本的完整文件路径。'],
	argInputFile: ['A temporary file containing the input data for the current testcase.', '由 CPH 生成的临时文件，包含当前测试用例的输入数据。'],
	argOutputFile: ['A temporary file containing the actual output generated by your code.', '由 CPH 生成的临时文件，包含您的程序生成的实际输出。'],
	outputDifference: ['Output Difference:', '输出差异：'],
	customChecker: ['Custom Checker', '自定义判题脚本'], customCheckerEnabled: ['Custom Checker (Enabled)', '自定义判题脚本 (已启用)'],
	customCheckerPathPlaceholder: ['Full path to Python script', 'Python 脚本的完整路径'],
	customCheckerDescription: ['CPH passes the input and actual output file paths to your Python script. Exit code 0 means passed; nonzero means failed. Expected output is ignored.', 'CPH 将输入和程序实际输出的临时文件路径传给 Python 脚本。退出代码 0 表示通过，非零表示失败。预期输出将被忽略。'],
	checkerLog: ['Checker Log', '判题日志'], checkerInvocation: ['Checker Invocation:', '判题脚本调用：'], checkerOutput: ['Checker Output:', '判题脚本输出：'],
	checkerExitCode: ['Checker Exit Code:', '退出代码：'], checkerDuration: ['Checker Duration:', '执行耗时：'], openChecker: ['Open the checker script', '打开判题脚本'],
	empty: ['No CPH problem is associated with this document.', '此文档没有关联的 CPH 题目。'],
	createProblem: ['Create Problem', '创建题目'],
	runAll: ['Run All', '运行全部'], save: ['Save Samples', '保存样例'], stop: ['Stop', '停止'], add: ['New Testcase', '新建测试用例'],
	passedRate: ['passed', '通过'],
	compileOnly: ['Compile without running', '仅编译，不运行'], moreActions: ['More actions', '更多操作'],
	delete: ['Delete testcases', '删除测试用例'], settings: ['Settings', '设置'],
	noSamples: ['No samples. Add a sample before running.', '暂无样例，请添加后再运行。'],
	passed: ['Sample passed', '样例通过'], 'wrong-answer': ['Wrong answer', '答案不符'], 'runtime-error': ['Runtime error', '运行错误'],
	'time-limit': ['Time limit', '超时'], cancelled: ['Cancelled', '已取消'], 'output-limit': ['Output limit', '输出超限'],
	copiedToClipboard: ['Copied', '已复制'], copy: ['Copy', '复制'], expand: ['Expand', '展开'], minimize: ['Collapse', '折叠'],
	copyFailed: ['Could not copy. Select the text and copy manually.', '复制失败，请选中文本手动复制。'],
	running: ['Running', '运行中'], checking: ['Checking', '检查中'], runAgain: ['Run this sample', '运行本例'], deleteTestcase: ['Delete sample', '删除样例'],
	inputLabel: ['Input:', '输入：'], expectedOutputLabel: ['Expected Output:', '预期输出：'], receivedOutputLabel: ['Received Output:', '实际输出：'],
	standardError: ['Standard Error (debug)', '标准错误（调试）'], runToShowOutput: ['Run to show output', '运行后显示输出'],
	setAsExpectedOutput: ['Use as expected output', '设为期望输出'], set: ['Set', '设为期望'], timedOut: ['Timed out', '超时'],
	compiling: ['Compiling', '编译中'], importTestcases: ['Import Testcases', '导入测试用例'], importTooltip: ['Import testcases from JSON', '从 JSON 导入测试用例'],
	testcasesImported: ['Imported {count} testcase(s).', '已导入 {count} 个测试用例。'], invalidImport: ['Invalid testcase JSON.', '测试用例 JSON 无效。'],
	importTooLarge: ['The testcase file is too large.', '测试用例文件过大。'], tooManyCases: ['At most 100 testcases are supported.', '最多支持 100 个测试用例。']
};

export function judgeTranslations(language: string): Record<string, string> {
	return Object.fromEntries(Object.entries(labels).map(([key, value]) => [key, value[language.toLowerCase().startsWith('zh') ? 1 : 0]]));
}

interface UiResult {
	diff?: DiffResult;
	checkerRun?: CheckerRun;
	pass: boolean; verdict: string; stdout: string; stderr: string; signal: string | null; timeOut: boolean; time: number;
}

export class JudgeView implements vscode.WebviewViewProvider, vscode.Disposable {
	static readonly id = 'becoder.cph.judge';
	private view: vscode.WebviewView | undefined;
	private readonly subscriptions: vscode.Disposable[] = [];
	private readonly session: JudgeSession;
	private results = new Map<number, UiResult>();
	private message = '';
	private busy = false;
	private savingSamples = false;
	private disposed = false;
	private dirty = false;
	private selectedId: number | undefined;
	private activeId: number | undefined;
	private phase: 'compile' | 'running' | 'checking' | undefined;
	get isBusy(): boolean { return this.busy || this.session.busy; }
	get hasUnsavedEdits(): boolean { return this.dirty; }
	get source(): string | undefined { return this.session.current?.problem.srcPath; }

	constructor(private readonly context: vscode.ExtensionContext) {
		const helper = path.join(context.extensionPath, '..', 'danielpinto8zz6.c-cpp-compile-run', 'dist', 'runner-input.exe');
		const executor = new CphExecutor({ extensionPath: context.extensionPath, dataRoot: path.join(context.globalStorageUri.fsPath, 'cph-sessions'), inputHelper: helper,
			onCompileStarted: () => this.progress('compile'),
			onCompileFinished: () => this.progress(undefined),
			onSampleStarted: index => {
				const id = this.selectedId ?? this.session.current?.problem.tests[index]?.id;
				if (id !== undefined) { this.results.delete(id); }
				this.progress('running', id);
			},
			onCheckerStarted: () => this.progress('checking', this.activeId),
			onSampleFinished: (index, sample) => {
				const id = this.selectedId ?? this.session.current?.problem.tests[index]?.id;
				if (id === undefined) { return; }
				const result = this.presentResult(id, sample);
				this.results.set(id, result);
				void this.view?.webview.postMessage({ command: 'result', id, result });
				this.progress(undefined);
			},
			preferences: source => {
				const config = vscode.workspace.getConfiguration('becoder.cph', vscode.Uri.file(source));
				return { timeOut: config.get('general.timeOut', 3000), ignoreSTDERROR: config.get('general.ignoreSTDERROR', true), pythonCommand: config.get('language.python.Command', 'python3'), compilerArgs: config.get(/\.c$/i.test(source) ? 'language.c.Args' : 'language.cpp.Args', '') };
			} });
		this.session = new JudgeSession(executor, async source => {
			if (!vscode.workspace.isTrusted) { throw new Error(vscode.l10n.t('Trust this workspace before running samples.')); }
			const document = await vscode.workspace.openTextDocument(vscode.Uri.file(source));
			if (!await document.save()) { throw new Error(vscode.l10n.t('Could not save the source file.')); }
		});
	}

	async open(problem: StoredProblem): Promise<void> {
		await this.openSource(problem.srcPath, vscode.workspace.getConfiguration('becoder.cph').get<boolean>('autoShowJudge', true));
	}

	async openAssociated(source: string): Promise<void> {
		if (this.session.current?.problem.srcPath === source) { return; }
		if (!new ProblemStore(path.dirname(source)).load(source)) { await this.clear(); return; }
		const focus = !this.view && vscode.workspace.getConfiguration('becoder.cph', vscode.Uri.file(source)).get('autoShowJudge', true);
		await this.openSource(source, focus);
	}

	async clear(): Promise<void> {
		if (this.isBusy || this.dirty) { return; }
		this.session.clear();
		this.results.clear();
		this.message = '';
		await this.publish();
	}

	async openSource(source: string, focus = true): Promise<void> {
		if (this.isBusy) { throw new Error(vscode.l10n.t('CPH is busy. Stop the current request first.')); }
		if (this.dirty) { throw new Error(vscode.l10n.t('Save the edited samples before opening another problem.')); }
		this.session.open(source);
		this.results.clear();
		this.message = '';
		if (focus) { await vscode.commands.executeCommand(`${JudgeView.id}.focus`); }
		await this.publish();
	}

	async runSource(source: string): Promise<void> {
		if (this.session.current?.problem.srcPath === source && this.view) {
			if (this.isBusy && !this.savingSamples) { return; }
			await this.view.webview.postMessage({ command: 'requestRun' });
			return;
		}
		await this.openSource(source);
		const current = this.session.current;
		if (!current) { return; }
		await this.receive({ command: 'run', revision: current.revision, tests: current.problem.tests, customCheckerPath: current.problem.customCheckerPath });
	}

	resolveWebviewView(view: vscode.WebviewView): void {
		this.view = view;
		const dist = vscode.Uri.joinPath(this.context.extensionUri, 'dist');
		view.webview.options = { enableScripts: true, localResourceRoots: [dist] };
		const script = view.webview.asWebviewUri(vscode.Uri.joinPath(dist, 'judge.js'));
		const css = view.webview.asWebviewUri(vscode.Uri.joinPath(dist, 'judge.css'));
		const nonce = randomUUID().replace(/-/g, '');
		const translations = JSON.stringify(judgeTranslations(vscode.env.language)).replace(/</g, '\\u003c');
		view.webview.html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${nonce}'; style-src ${view.webview.cspSource} 'unsafe-inline'; font-src ${view.webview.cspSource};">
<link rel="stylesheet" href="${css}"></head><body><div id="app"></div>
<script nonce="${nonce}">window.translations=${translations};</script><script nonce="${nonce}" src="${script}"></script></body></html>`;
		this.subscriptions.push(view.webview.onDidReceiveMessage(message => { void this.receive(message); }));
		this.subscriptions.push(view.onDidDispose(() => { if (this.view === view) { this.view = undefined; } }));
	}

	private async receive(message: unknown): Promise<void> {
		if (this.disposed || !message || typeof message !== 'object') { return; }
		const request = message as { command?: string; revision?: unknown; tests?: unknown; id?: unknown; customCheckerPath?: unknown };
		if (request.command === 'dirty') { this.dirty = true; return; }
		if (request.command === 'ready') { await this.publish(); return; }
		if (request.command === 'stop') { this.session.cancel(); return; }
		if (request.command === 'settings') { await vscode.commands.executeCommand('workbench.action.openSettings', '@ext:becoder.cph'); return; }
		if (request.command === 'createProblem') { await vscode.commands.executeCommand('becoder.cph.openCurrent'); return; }
		if (request.command === 'openChecker') {
			if (!vscode.workspace.isTrusted || this.isBusy || !this.session.current) { return; }
			const checker = this.session.current.problem.customCheckerPath?.trim();
			if (checker) {
				try { await vscode.window.showTextDocument(vscode.Uri.file(path.resolve(path.dirname(this.session.current.problem.srcPath), checker))); }
				catch (error) { await vscode.window.showErrorMessage(String(error)); }
			}
			return;
		}
		if (!['save', 'run', 'compile', 'delete'].includes(request.command ?? '')) { return; }
		if (this.isBusy) { return; }
		this.busy = true;
		this.savingSamples = request.command === 'save';
		let failed = false;
		try {
			if (!vscode.workspace.isTrusted) { throw new Error(vscode.l10n.t('Trust this workspace before running samples.')); }
			if (request.customCheckerPath !== undefined && typeof request.customCheckerPath !== 'string') { throw new Error(vscode.l10n.t('Invalid sample request.')); }
			if (typeof request.revision !== 'string' || (request.id !== undefined && !Number.isSafeInteger(request.id))) {
				throw new Error(vscode.l10n.t('Invalid sample request.'));
			}
			if (request.command === 'delete') {
				const snapshot = this.session.current;
				if (!snapshot || request.revision !== snapshot.revision) { throw new Error('Problem changed.'); }
				const remove = vscode.l10n.t('Delete Testcases');
				if (await vscode.window.showWarningMessage(vscode.l10n.t('Delete this problem’s testcases? Your source code will be kept.'), { modal: true }, remove) === remove) {
					const store = new ProblemStore(path.dirname(snapshot.problem.srcPath));
					const release = await acquireWorkspaceLease(store.root);
					try {
						if (store.load(snapshot.problem.srcPath)?.revision !== snapshot.revision) { throw new Error('Problem changed.'); }
						await vscode.workspace.fs.delete(vscode.Uri.file(snapshot.metadataPath), { useTrash: true });
					} finally { await release(); }
					this.session.open(snapshot.problem.srcPath);
					this.results.clear();
					this.dirty = false;
					this.message = '';
				}
			} else if (request.command === 'save') {
				await this.session.save(request.revision, request.tests, request.customCheckerPath as string | undefined);
				this.dirty = false;
				this.message = '';
			} else {
				this.message = vscode.l10n.t('Compiling and running samples…');
				const pending = this.session.run(request.revision, request.tests, request.id as number | undefined, request.command === 'compile', request.customCheckerPath as string | undefined);
				this.selectedId = request.id as number | undefined;
				const { run, ids } = await pending;
				this.dirty = false;
				for (const [index, sample] of run.samples.entries()) {
					this.results.set(ids[index], this.presentResult(ids[index], sample));
				}
				if (run.compile.exitCode !== 0 || run.compile.launchError || run.compile.cancelled || run.compile.timedOut || run.compile.outputLimitExceeded) {
					this.message = vscode.l10n.t('Compilation did not complete successfully.\n{0}', stripVTControlCharacters(run.compile.launchError ?? run.compile.stderr).slice(0, 100000));
				} else if (request.command === 'compile') {
					this.message = vscode.l10n.t('Compilation succeeded.');
				} else {
					this.message = vscode.l10n.t('{0} / {1} samples passed.', run.samples.filter(sample => sample.verdict === 'passed').length, ids.length);
				}
				if (run.compile.exitCode === 0 && !vscode.workspace.getConfiguration('becoder.cph').get('general.hideStderrorWhenCompiledOK', true) && run.compile.stderr) {
					this.message += '\n' + displayOutput(stripVTControlCharacters(run.compile.stderr), vscode.l10n.t('[Output truncated]'));
				}
			}
		} catch (error) {
			failed = true;
			this.message = vscode.l10n.t('CPH request failed: {0}', error instanceof Error ? error.message : String(error));
		} finally {
			this.busy = false;
			this.savingSamples = false;
			this.phase = undefined;
			this.activeId = undefined;
			if (failed) {
				await this.view?.webview.postMessage({ command: 'failure', message: this.message, revision: this.session.current?.revision });
			} else if (request.command === 'save') {
				await this.view?.webview.postMessage({ command: 'saved', revision: this.session.current?.revision });
			} else { await this.publish(); }
		}
	}

	private progress(phase: typeof this.phase, id?: number): void {
		this.phase = phase;
		this.activeId = id;
		void this.view?.webview.postMessage({ command: 'progress', phase, id });
	}

	private presentResult(id: number, sample: JudgeRun['samples'][number]): UiResult {
		return { pass: sample.verdict === 'passed', verdict: sample.verdict,
			diff: !sample.checkerRun && sample.verdict === 'wrong-answer' ? diffOutput(this.session.current?.problem.tests.find(item => item.id === id)?.output.slice(0, 100000) ?? '', sample.result.stdout.slice(0, 100000)) : undefined,
			checkerRun: sample.checkerRun && { ...sample.checkerRun, stdout: displayOutput(stripVTControlCharacters(sample.checkerRun.stdout), vscode.l10n.t('[Output truncated]')), stderr: displayOutput(stripVTControlCharacters(sample.checkerRun.launchError ?? sample.checkerRun.stderr), vscode.l10n.t('[Output truncated]')) },
			stdout: displayOutput(sample.result.stdout, vscode.l10n.t('[Output truncated]')),
			stderr: displayOutput(stripVTControlCharacters(sample.result.stderr), vscode.l10n.t('[Output truncated]')),
			signal: sample.result.launchError ?? sample.result.signal,
			timeOut: sample.result.timedOut, time: sample.result.durationMs ?? 0 };
	}

	private async publish(): Promise<void> {
		if (!this.view || this.disposed) { return; }
		const current = this.session.current;
		const python = vscode.workspace.getConfiguration('becoder.cph').get('language.python.Command', 'python3');
		await this.view.webview.postMessage({ command: 'state', state: {
			revision: current?.revision ?? '', name: current?.problem.name ?? '', source: current?.problem.srcPath ?? '', url: current?.problem.url ?? '', local: current?.problem.local === true,
			busy: this.isBusy, message: this.message, phase: this.phase, activeId: this.activeId,
			customCheckerPath: current?.problem.customCheckerPath ?? '',
			pythonCommand: process.platform === 'win32' && python === 'python3' ? 'python' : python,
			hideOutputDifference: vscode.workspace.getConfiguration('becoder.cph').get('general.hideOutputDifference', true),
			cases: current?.problem.tests.map(testcase => ({ id: testcase.id, testcase, result: this.results.get(testcase.id) ?? null })) ?? []
		} });
	}

	dispose(): void {
		this.disposed = true;
		this.session.dispose();
		for (const disposable of this.subscriptions) { disposable.dispose(); }
	}
}
